version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app               
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      SECRET_KEY: "LESTA"
    command: flask run --host=0.0.0.0
